### ISSUE TITLE
Shouldn't the `.cruft.json` file be versioned ?

### ISSUE THREAD

**Issue by achedeuzot** [cruft/cruft#100]
This is not an issue. It's more of a future-proof idea.

The file created by cruft should be versioned to support updates across time and versions.

This will allow the `.cruft.json` file content to evolve its schema over time.

**Comment by languitar** [comment]
I think what is missing here is to automatically stage the file.

**Comment by sambhav** [comment]
It's a good idea. We can re-consider it with v3 of cruft. Closing this issue for now.
