### ISSUE TITLE
Support non-git paths

### ISSUE THREAD

**Issue by kevinkjt2000** [cruft/cruft#113]
I would like to bundle some cookiecutter project templates with a developer scaffolding/workflow tool that I'm creating. I realized it would be wonderful if the scaffolding part of this tool could help merge in template updates. This is when I discovered cruft and tried to integrate the `cruft.create` and `cruft.update` API's into the tool.

Unfortunately, cruft seems to rely on the template being a git repo. The installed path of a python module does not contain the git repo stuff, so cruft is unable to create the template from a sub-directory of the install location. Here's a reproduction of what I'm talking about with all the complexity of the tool that I'm working on abstracted away:

```
mkdir new-folder
cd new-folder
echo '{"var": "blah"}' > cookiecutter.json
mkdir {{cookiecutter.var}}
touch {{cookiecutter.var}}/something.txt
cruft create . --output-dir=../plz-work
```

```
Error: Unable to initialize the cookiecutter using /private/tmp/new-folder! Failed to clone the repo. stderr: 'fatal: repository '/private/tmp/new-folder' does not exist
'
```

It seems local paths do not work if the path does not contain a git repo. I believe the error message is from `git clone` failing. Cookiecutter can generate this okay. #110 mentions that local paths are meant to be supported, but it seems the library is limiting this to cloned git repositories only? Is this intentional? Or just a missing feature?

As a workaround, I tried to `cruft.link` after using cookiecutter to generate the template; however, that results in the same error expecting a git repo.

I investigated why this might be and realized that the `.cruft.json` file is tracking the commit ref of the git repo. Presumably, this is used to quickly detect the presence of differences during updates? I'm wondering if it would be possible to `null` this for local paths?

Thoughts? Ideas? Must the templates be git repositories for the update feature to function?

**Comment by samj1912** [comment]
Cruft only works with git templates. Otherwise it doesn't have any way to track which template revision the generated project is on and which one to update to. For cruft to track and find diffs between two template versions, the template itself needs to be a git repository. If you only want to generate a one off project from a non git template, just plain cookiecutter should work.

**Comment by kevinkjt2000** [comment]
In hindsight, I realize it was a silly idea to bundle the templates with the tool that I'm making. I would have had to ship every version of each template bundled with it in order to do the 3-way diffs for merging. It does make sense to give each of those their own repo. Thanks!

**Comment by gregl83** [comment]
I've come across this issue with a monorepo maintaining some templates.

Is it possible to create a project based off a path within a git project?

**Comment by awesomescot** [comment]
I agree with @gregl83.  I'm also working on a monorepo and would like to have some templates within the repo that the many micro services are built from and updated when I update the template.  Maybe cruft isn't the tool for this, but cookiecutter doesn't seem to have these update and diff options.
