### ISSUE TITLE
Updating template from project ?

### ISSUE THREAD

**Issue by dleurs** [cruft/cruft#117]
Hello,

Is it possible to update template from a project generated by the template ?

I like the fact that project can be easily updated from the template, but it seems I have to modify my template "by hand".

For example, if I added a ```print("Hello World");``` in a project and I want it to be present in the original template (and then all other projects), i have to copy-paste it from project to template, and finally commit-push inside the template.

It can be very long to copy/paste all the code created inside a project to the template, and it is a very bug-friendly mistake-friendly operation.

I cannot develop from the template directly because of all the ```{{ }}``` that does not make the code compile. (I am currently coding on Dart for Flutter)

**Comment by dleurs** [comment]
I will look at https://retrocookie.readthedocs.io/en/latest/

**Comment by sambhav** [comment]
Retrocookie looks like a more targeted project for your use case.
