### ISSUE TITLE
Feature request: provide homebrew package

### ISSUE THREAD

**Issue by luisdavim** [cruft/cruft#119]
Hi, would it be possible to provide cruft as a bew package?

**Comment by shmygol** [comment]
I think I can do that.

**Comment by shmygol** [comment]
Looks like the description is too long. Should be only 80 symbols. @samj1912 Would the following work work for you?
```
Utility that creates projects from templates and maintains the cruft afterwards
```

**Comment by samj1912** [comment]
sgtm

**Comment by shmygol** [comment]
https://github.com/Homebrew/homebrew-core/pull/83399

**Comment by mmatthews06** [comment]
It looks like they merged this, FYI:
https://github.com/Homebrew/homebrew-core/pull/83399

I just tried installing cruft with brew, and it works. Well done!

**Comment by samj1912** [comment]
Amazing! Thanks!
