### ISSUE TITLE
Detect and update old sphinx config

### ISSUE THREAD

**Issue by abitrolly** [cruft/cruft#122]
Curious if `cruft` could detect which Sphinx version was used to generate `Makefile`,`conf.py`, `make.bat` like in https://github.com/lambdaloop/anipose/tree/master/docs/sphinx and propose to upgrade them.

**Comment by samj1912** [comment]
@abitrolly I am not sure if I understand what you mean here. cruft relies on cookiecutter and does not explicitly contain any special logic to handle certain kinds of applications/libraries. If there is a cookiecutter[1] that sets up and keeps sphinx related files up-to-date, cruft should be able to update it.

As such I am closing the issue. Feel free to re-open the issue if I misunderstood what you mean.

[1] - https://github.com/cookiecutter/cookiecutter
