### ISSUE TITLE
Feature request: Faster implementation for cruft check

### ISSUE THREAD

**Issue by jonzarecki** [cruft/cruft#123]
I see from the source code that `cruft check` is cloning the repo only to get the last commit's hash.
I can see this tends to be quite slow 30+ seconds. I'm thinking that there must be another way to make this check faster, and only clone the repo for `cruft diff` or `cruft update`.

I'm willing to contribute if we'll think about an implementation method.
Thanks! 🤗

**Comment by samj1912** [comment]
It should definitely be possible to improve this. The first thing I can think of is to only fetch the commit instead of the entire repository. That should help speed things up.

**Comment by jonzarecki** [comment]
Well, this was a short search.

This seems like a good option: https://stackoverflow.com/a/60952814

The process should be:
```bash
git clone --filter=blob:none --no-checkout --single-branch https://repo_url.git tmpdir
cd tmpdir
git log
```

I'm not sure about all the flags but `git log` seems to work on the main branch.
