### ISSUE TITLE
cruft 2.9.0 on Pypi requires click <= 8.0.0

### ISSUE THREAD

**Issue by jlec** [cruft/cruft#124]
The setup.py shipped on Pypi has an old version of click fixed as depdency. I cannot find any reference in the repo for that requirement. can you please update the tarball?

**Comment by jlec** [comment]
It seems to originate from typer which requires old click.

**Comment by mmatthews06** [comment]
This would be nice for me as well, as I'm developing a different set of tools that use Click 8+, that we're also having people install with `--user`, so we're seeing some conflicts if you use the same python environment.
