### ISSUE TITLE
[Question] Are there python functions to call cruft create, update, and check?

### ISSUE THREAD

**Issue by simkimsia** [cruft/cruft#134]
Is there a way to use cruft as a python library instead of cli?

Right now I call cookiecutter (v.1.7.3) as a python function

```
_ = cookiecutter(
        template=git_repo_url,
        no_input=True,
        extra_context={"project_name": project_name, **context},
        output_dir=tmpdir,
        directory="",
    )
```

where the template is a url to a git repository. 

can i do the same with cruft? and by pointing to a github repository?

EDIT:

### Create

I suppose for create, I can use this?

https://github.com/cruft/cruft/blob/3ec724634d8509d37164f2473ddf8674f072474c/cruft/_commands/create.py#L12

**Comment by samj1912** [comment]
Yes, they are documented at https://cruft.github.io/cruft/reference/cruft/.
