### ISSUE TITLE
Config in pyproject.toml or .cruft.json?

### ISSUE THREAD

**Issue by birdcolour** [cruft/cruft#140]
Hi, great tool!

Just checking I've understood the way the config works - presently, everything can be configured via the `.cruft.json` file, but skip files can also be configured in the `pyproject.toml` file, if desired (and with cruft installed with the `[toml]` extra).

If I'm correct - is there a particular reason that the whole config could not also be detected from `pyproject.toml` file? It's not exactly a dealbreaker, but it would be nice if a project that helps us manage and reduce cruft does not introduce another small file into the root of every project we use it with! :)

**Comment by baggiponte** [comment]
Hello, I am also interested in whether `cruft` supports configs in `pyproject.toml` - for example, does `cruft` support the following?

```toml
[tool.cruft]
template = "blablabla"
```

The use case for this would be that `cruft check` defaults to the settings there.

If the answer is no, I would love to contribute to contribute. The way I see it, it's a bit like `ruff`: a `--config` flag that defaults to the top level `pyproject.toml`.

**Comment by Pinzauti** [comment]
Is there any news about this?

**Comment by Tatsh** [comment]
This won't work well if you use cookiecutter to template out the pyproject.toml file.

**Comment by sambhav** [comment]
Closing this as a won't fix because of the above outlined issue (re: generating pyproject.toml as part of the output repo)
