### ISSUE TITLE
UserWarning: pyproject.toml is present in repo, but `toml` package is not installed. Cruft configuration may be ignored.

### ISSUE THREAD

**Issue by tekumara** [cruft/cruft#145]
```
/Users/tekumara/.local/pipx/venvs/cruft/lib/python3.9/site-packages/cruft/_commands/utils/generate.py:104: UserWarning: pyproject.toml is present in repo, but `toml` package is not installed. Cruft configuration may be ignored.
```

occurs on a project with a pyproject.toml. We only use pyproject.toml for project settings, not for cruft. 

To avoid this warning, would it be possible to bundle toml as a dependency of cruft?

**Comment by samj1912** [comment]
It is bundled if you install cruft via `cruft[pyproject]`

**Comment by tekumara** [comment]
Ah right thanks, I had no idea. Having it bundled as part of the main package would probably still be useful, I'm probably going to forget to include pyproject next time 😅
