### ISSUE TITLE
Upgrade version of importlib-metadata

### ISSUE THREAD

**Issue by adamcunnington-mlg** [cruft/cruft#152]
Currently, cruft pins the major version of importlib-metadata to 3. This is really out of date.

[importlib-metadata](https://pypi.org/project/importlib-metadata/) is currently at v4.11.3

The latest version of sphinx requires at least v4.4 of importlib-metadata and so currently, there is an incompatibility that is forcing me to use an old version of sphinx.

Please simply change [this line](https://github.com/cruft/cruft/blob/0c6de85d974197969c0e65913857eaa36b788e5e/pyproject.toml#L17) to me some more recent version (e.g. `">=3.4"`)

@samj1912 are you happy with this?

**Comment by samj1912** [comment]
Sounds good to me :)

**Comment by adamcunnington-mlg** [comment]
@samj1912 as maintainer, will you make this fix and pypi release? 
Thank you

**Comment by maresb** [comment]
Closed by #154
