### ISSUE TITLE
Local extensions don't work with (Cookiecutter 2.1.1)

### ISSUE THREAD

**Issue by danielkza** [cruft/cruft#172]
The standard examples for local extensions in the Cookiecutter docs don't work with cruft. Creating a `local_extensions` folder with an `__init__.py`, or a `local_extensions.py` file in the root of the template should make `local_extensions` importable as a module, but it fails with Cruft because the working directory is not set to the path of `cookiecutter.json` (or alternatively, the Python search path is updated to include that directory).

**Comment by jensfriisnielsen** [comment]
I just found the same thing.

**Comment by skjoedt** [comment]
Are there any known work around for shipping extensions with cruft templates?

**Comment by stefan-caraiman** [comment]
bump, any updates on this? it's quite blocking
