### ISSUE TITLE
How to apply template to existing Git/GitHub project? 

### ISSUE THREAD

**Issue by andreas-vester** [cruft/cruft#176]
What's the best way to apply a cruft template to an existing Git/GitHub project,  which doesn't use any cookiecutter template at all?

**Comment by JulianSobott** [comment]
Probably not the best solution but worked for me.
1. Create a new project using the template
2. Copy the newly created files into the existing project dir. This may overwrite existing files, but you have all changes in your git history.
3. Review all changes manually using `git diff` or graphical git tools
5. Commit your changes

**Comment by amaslenn** [comment]
Thanks @JulianSobott!

But `cruft` also has `link` functionality, why doesn't it create new files/folders according to the template? I've just stuck with it, not the behavior I expect.

**Comment by andreas-vester** [comment]
@JulianSobott
This solution worked for me. Thanks!
