### ISSUE TITLE
Cruft update only to released version of template

### ISSUE THREAD

**Issue by grst** [cruft/cruft#183]
Is it possible to use `cruft check` / `cruft update` such that it only updates to the latest released version of a template? 
Something like
```
cruft update --latest-release
```

Background:
I'm trying to set-up automated template sync using github actions by running `cruft update` nightly and automatically create a pull request if there were updates. To reduce the traffic on the target repo, I would prefer if a pull request were created only if a new version of the template was released, rather than on every single commit.

**Comment by grst** [comment]
Can I judge by the "good first issue" label that you would accept a PR for this? 

What about the interface? 
```
--latest-release
```
sounds good?

**Comment by clotildeguinard** [comment]
Hi! I have a naive question, how do you define "release"? a git tag? I can see that with github, there is a specific notion of releases that you can list with the github CLI. But this won't generalize to all git-based versioning services?

**Comment by grst** [comment]
A github release implies a tag. Would using the latest tag work?

**Comment by clotildeguinard** [comment]
I am not sure "latest" tag criteria would be enough to target releases only, as one can create tags for a different purpose. This means that you should implement a custom logic for your own case, where you filter the tags depending on the tag pattern that you expect for a release... That logic would belong in a script that the github action would run, and that would end with "cruft update --checkout <selected-tag>". 

(note: this is only my view, you may want to get additional advice from cruft maintainers)

**Comment by grst** [comment]
Good point! My thought was that templates tend to have more simple versioning systems (e.g. no backports to older versions). 

But actually I think your suggestion to use `--checkout` works well for my use-case!
