### ISSUE TITLE
Persist checkout branch when linking a project

### ISSUE THREAD

**Issue by clotildeguinard** [cruft/cruft#184]
# Problem to solve 

Currently, the "create" commmand does persist the checkout parameter in the .cruft.json file.

But the "link" command does not, instead it only stores the latest commit of the related reference.

# Example (how to reproduce)

(cruft 2.11.1, cookiecutter 2.1.1)

As an example, if one does:

`cookiecutter git@github.com:cruft/cookiecutter-test.git -c updated --directory dir`

where the latest commit on branch "updated" is `14efb4015737cb5179ba7afafb3c08fe661557c0`

and then

`cruft link git@github.com:cruft/cookiecutter-test.git -c updated --directory dir`

then the `.cruft.json` contains the following:

> {
>   "template": "git@github.com:cruft/cookiecutter-test.git",
>   "commit": "14efb4015737cb5179ba7afafb3c08fe661557c0",
>   "context": {
>     "cookiecutter": {
>       "project": "test",
>       "_template": "git@github.com:cruft/cookiecutter-test.git"
>     }
>   },
>   "directory": "dir"
> }

Whereas if one directly does:

`cruft create git@github.com:cruft/cookiecutter-test.git -c updated --directory dir`

then the `.cruft.json` contains the following:
        
> {
>   "template": "git@github.com:cruft/cookiecutter-test.git",
>   "commit": "14efb4015737cb5179ba7afafb3c08fe661557c0",
>   "checkout": "updated",
>   "context": {
>     "cookiecutter": {
>       "project": "test",
>       "_template": "git@github.com:cruft/cookiecutter-test.git"
>     }
>   },
>   "directory": "dir"
> }

We would expect to get exactly the same content in `.cruft.json` in both cases, but as one can see, the "checkout" key is missing in the first case because the "link" command does not store the "checkout" parameter.

# Related issues

Relates to #92, #54

**Comment by jannickj** [comment]
this feature does not work for me i get

```
$ cruft update
╭─ Error ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Was unable to locate a Cookiecutter template in `/tmp/tmpnu4bkrck/repo` !                                                                                     │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

```
