### ISSUE TITLE
Feature Request: Create an Anaconda/Conda-Forge package

### ISSUE THREAD

**Issue by Zeitsperre** [cruft/cruft#22]
Neat library. Just started using it on some of my cookiecutter-built repos. I can see this being really great for dealing with multiple projects started from the same boilerplate.

One thing that I would like to see is an Anaconda binary for this package. Creating a new build reciple for Conda-Forge (https://conda-forge.org/#add_recipe) is very easy, largely based off of your setup.py. If you'd like, I can help with this.

Thanks for maintaining the library!

**Comment by samj1912** [comment]
I don't think we have any plans of supporting conda installs in the near future or publishing to conda forge. But if you are willing help out with the maintenance of the binary, that'd be great. Please feel free to create the forge recipe :)

**Comment by samj1912** [comment]
Fixed by #50
