### ISSUE TITLE
A new Cookiecutter community fork named Cookieninja

### ISSUE THREAD

**Issue by yuvaldolev** [cruft/cruft#221]
Unfortunately it seems that the Cookiecutter project is on hiatus, and new issues (including ones that are required by the cruft project) aren't being worked on.

We started working on a new community fork of the Cookiecutter project, named Cookieninja.
The fork is found at: https://github.com/cookieninja-generator/cookieninja

We have re-opened and merged the many of the PRs from the Cookiecutter project in Cookieninja, including the PR by @simonwardjones that fixes cruft issue #166 (the PR is at https://github.com/cookieninja-generator/cookieninja/pull/34)

We're trying to bring the life back to the Cookiecutter project.
We are committed to addressing each issue in up to 1 week from the day it's opened, and reviewing and merging each PR in up to 2 weeks from the day it's opened (if there are no issues with it).
We'd really like you to join the fork, star it, contribute to it and create new issues!

Thank you :)

**Comment by ido-ran** [comment]
Is that means you might build cruft functionality into cookie ninja instead of layering it on top?

**Comment by sambhav** [comment]
Thanks for the informational issue. Given that Cookiecutter seems to be alive again, I'm closing this. We currently don't have plans on integration with alternative template generators.
