### ISSUE TITLE
Feature Request: Override flag for template URL in `cruft update`

### ISSUE THREAD

**Issue by JulianSobott** [cruft/cruft#244]
We want to use cruft in our GitLab CI/CD, to update projects automatically, when the template changes.
The problem is that to clone another Repository in the Pipeline, the Repository URL must contain an access token. We obviously don't want that token in our `.cruft.json` file, because it is secret, and we git over ssh for local development.

For `cruft check` a workaround was to, replace the template url with the url containing the access token in the pipeline, before the cruft check command.
This however no longer works, because `cruft update` needs a clean working directory.

My proposal would be to add a flag `--template` to the `update` command (and possibly others) to override the setting in the `.cruft.json`

**Comment by kemics** [comment]
exactly the same problem. It would be nice to have a solution
