### ISSUE TITLE
git submodules directories are not working

### ISSUE THREAD

**Issue by puria** [cruft/cruft#252]
Hola ;)

I have a multirepo cookiecutters template on gh. One of these templates is a git submodule.
when I run
```bash
cruft create --directory submodule-template-dir https://github.com/puria/templates
```
cruft is not able to create the project (guess does not clone recursively the submodules) with the following output:

```
Error: Was unable to locate a Cookiecutter template in `/tmp/tmpdbo2r3bi/**** !
```
is there a way make it work with git subomodules?

**Comment by sambhav** [comment]
Cruft should support git submodules as of 2.16.
