### ISSUE TITLE
Using Cruft from Python programmatically

### ISSUE THREAD

**Issue by andersbogsnes** [cruft/cruft#265]
Hi, big fan of the project! 

We have an in-house dev CLI for managing various dev tasks and I would like to use cruft under the hood for managing config files. 

I don't see any "safe" way to use cruft programmatically, like I can with cookiecutter. Is that something you'd be willing to consider supporting?

**Comment by samj1912** [comment]
@andersbogsnes we certainly support programmatically accessing cruft methods. See https://cruft.github.io/cruft/reference/cruft/

**Comment by andersbogsnes** [comment]
Ah, thanks for the reference! Just looked at the code and saw everything was underscored and didn't see anything in the docs. Glad to hear it!
