### ISSUE TITLE
is it possible to use cruft not with commit hash but release tags instead ? 

### ISSUE THREAD

**Issue by 12rambau** [cruft/cruft#270]
Everything is in the title, I develop one of my cookiecutter as a lib and use tags to notify other users from a new release. I want to use cruft to make the update more automatic but it seems the lib is only looking at commit hash to check if update is needed. Is it possible to work with tags instead ?

**Comment by eperdeme** [comment]
We run cruft with ```cruft update -c 5.0.0``` which works fine for tags for us.

**Comment by 12rambau** [comment]
excellent thanks !
