### ISSUE TITLE
`cruft diff` fails for `cookiecutter` local extensions

### ISSUE THREAD

**Issue by fabrykato** [cruft/cruft#289]
## Issue
Since PR #237 (fixing #172) it is possible to `cruft upgrade` and `cruft check` `cookiecutter` templates including [local extensions](https://cookiecutter.readthedocs.io/en/2.6.0/advanced/local_extensions.html).

But the fix was incomplete, because `cruft diff` still complains like this: 

```
UnknownExtension: Unable to load extension: No module named 'local_extensions'
```

## Solution

The reason is in the different handling of `cruft`'s `directory` parameter in [diff](https://github.com/cruft/cruft/blob/master/cruft/_commands/diff.py) and [upgrade](https://github.com/cruft/cruft/blob/master/cruft/_commands/update.py) command, although they handle the directories similar.

I'll provide a PR for this.

## Versions
- `cruft==2.15.0`
- `cookiecutter==2.4.0`

**Comment by Fabi89** [comment]
Hi, from my point of view, this PR is ready to be merged. Is someone reviewing?
