### ISSUE TITLE
Pypi release not up to date

### ISSUE THREAD

**Issue by adanaja** [cruft/cruft#308]
Hello, I am interested in this feature https://github.com/cruft/cruft/pull/264 adding the `--extra-context-file` argument, but when testing I see that while the PR has been merged on Jul 8, 2023, the version released on pypi is from May 11, 2023 https://pypi.org/project/cruft/#files

Is there any plan releasing a new version with that feature?

**Comment by sambhav** [comment]
A new release has been cut.
