### ISSUE TITLE
Inquiring about project maintenance

### ISSUE THREAD

**Issue by wdonofrio** [cruft/cruft#312]
Hi @timothycrosley and @samj1912

Thank you for building and maintaining Cruft over the years. I stumbled upon the project through a random YouTube video, and I use it today as a way to fan-out boilerplate code across projects. It's quite something :)

Fortunately, others are also excited about Cruft and are looking to improve it (based on the 83 issues and 25 PRs at time of writing). However, I wanted to check in regarding Cruft's maintenance. I've noticed there hasn't been much activity in over a year, despite continuous feedback and suggestions from the community. As a result, it seems the last release and PR merge was over a year ago.
All to ask: Is this project still being maintained?

I'd love to be contributor to improve Cruft, however, the lack of activity is concerning.

Thank you for your time!
William

**Comment by devinnasar** [comment]
I'm also interested in whether Cruft is being maintained. The only projects that seem to handle template updates are Cruft and Copier, but Copier doesn't support the concept of deploying multiple templates as subdirectories within a repo without them being git submodules. @samj1912 , can you shed some light on the maintenance cycle for Cruft?

**Comment by eshepelyuk** [comment]
Looks like @sambhav should be tagged instead of sam1912

**Comment by sambhav** [comment]
hello folks, I am currently on vacation but I will have some cycles near the end of the year where my goal is to go through major pending PRs and issues and merge/fix them.

I am also trying to figure out a more sustainable maintenance process and onboarding a few maintainers who can help. More details to follow in a couple weeks when I'm back.

**Comment by sambhav** [comment]
I will close this issue in about 2 weeks time when I actually get through to making a release.

**Comment by sambhav** [comment]
Started working on this again. Beginning with modernizing the ci/dev env.

**Comment by eshepelyuk** [comment]
Sir, more maintainers is the purpose of this issue :)
