### ISSUE TITLE
Add support for Windows (WSL is already supported) 

### ISSUE THREAD

**Issue by samj1912** [cruft/cruft#41]
With #36 and cruft 2.0 we officially dropped support for Windows. See #39 for the reasoning behind this change.

Creating this issue to track interest for adding back Windows support and to discuss how to implement the same.

**Comment by juhuebner** [comment]
1st: cruft: Great tool!

I managed some of the WIN problems get to work here: #85

**Comment by jonzarecki** [comment]
Just wanted to note that I'll be testing @juhuebner implementation for windows in the following days.

The fork that I'm working from is in [here](https://github.com/jonzarecki/cruft/).
It has @juhuebner updates + a merge from the current cruft state.

ATM it seems to work perfectly. I'll update if any issues pop up.

**Comment by jonzarecki** [comment]
Added a new PR with a continuation of @juhuebner's work from #85 in #125. 

Seems to be working fine for my team for the last 2 weeks, and the changes he made seem reasonable.

**Comment by jonzarecki** [comment]
Can you post the entire trace?
Are you able to run a normal cookiecutter create? (Without cruft)

**Comment by sharadpattanshetti** [comment]
Hi @jonzarecki, please find below entire trace:


`Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/cookiecutter/generate.py", line 352, in generate_files
    generate_file(
  File "/home/user/.local/lib/python3.8/site-packages/cookiecutter/generate.py", line 175, in generate_file
    rendered_file = tmpl.render(**context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/user/.local/bin/cruft", line 8, in <module>
    sys.exit(app())`

**Comment by jonzarecki** [comment]
Weird, I don't see, however `cruft` in the trace, did you try to just use `cookiecutter create`?

**Comment by samj1912** [comment]
Closed in #125

**Comment by sharadpattanshetti** [comment]
@jonzarecki yes used cookiecutter create but still get above error. Tried it with cruft v2.10.1 as well. 
 Python 3.8.10
Is there any specific python to be used?

**Comment by jonzarecki** [comment]
Not that I'm aware. Can you give us the steps to reproduce the error from scratch?
