### ISSUE TITLE
Update fails on moved files, without clear error messages. 

### ISSUE THREAD

**Issue by andrew-schweitzer-analog** [cruft/cruft#53]
I ran a cruft update from current rev to a more recent tag. The update failed, modifying _only_  `.cruft.json`. No .rej files are present and the error message does not, as far as I can tell, indicate which file the problem occurred with. The output is attached in a [file](https://github.com/cruft/cruft/files/5178229/cruft-update-fail.txt) (because its contents contains markdown that confuses the display of this issue.

Ideally: 
- The merge doesn't fail. This not addressable in general, and since this isn't an open source cookiecutter I can't share the specific steps to reproduce at the moment. 
- The error message about the diff / merge more clearly indicates which files have an issue. 
- If the merge fails, the merge failures *are* present. 
- If the merge fails, the output doesn't say 'Good work! Project's cruft has been updated and is as clean as possible!' in green. 

Maybe some debugging functionality would help. It might be useful to:
*  Preserve the downloaded cookiecutter-recipe repos, old and new, on which which the diff is produced.
*  Be able to run locally on from those old/new repos to help understand what diff is causing merge to fail.
* Have a verbose mode that would clearly print relevant directories, git commands etc.

**Comment by andrew-schweitzer-analog** [comment]
I _think the diff should be preserved as a file_, optionally or automatically if the apply fails. 

Once I manually modified the code to do that, it easy to isolate the problem, which was that `git apply` was failing on files that had moved between two commits. I assume there's not magic git command to solve that (and all other potential problems with an apply), so to ease troubleshooting, it would be nice if: 

1. The diff was preserved in a file, at least optionally, and/or if an error is detected in applying it. 
2. If the merge fails, cruft does _not_ say 'Good work!' in green, but gives an error (red would be nice). 
3. If the merge succeeds, but manual merges are necessary, _not_ say 'Good work!' in green, but gives a warning (yellow would be nice).
4. There was verbose mode that reported in a bit more detail what cruft was doing (for example, printing the git commands).

These perhaps should be 4 separate issues.

**Comment by peldszus** [comment]
I also ran into this issue. I used `git mv` to move/rename a file in the template.

When updating the project with the newest version of the template, the file is only removed in the old location, but not re-created in the new location. So, instead of being renamed, it is effectively deleted.
