### ISSUE TITLE
Feature request: ability to diff cruft

### ISSUE THREAD

**Issue by gilbsgilbs** [cruft/cruft#58]
Hi,

First of, thanks for making this fantastic project. It's a very nice improvement over cookiecutter and I'm relieved somebody tackled this problem.

The only thing I'm missing would be a way to check whether there's a diff between the remote template and the local one. If I'm not mistaken, the `check` command only checks for new commits in the remote which is not exactly what I want. My main use case is to ensure any improvement to the boilerplate is actually committed to the template and not to the local project, so that all other projects can benefit from the improvement.

Ideally (that may be another feature), if some projects using a cruft needs to apply some very specific changes to the template, they can either skip the whole files (which is already possible) or specify a set of patches to apply to the generated template. The patches could be specified in the `cruft.json` like so: `{"patches": [".cruftpatches/remove-useless-feature.patch]}`.

WDYT? I may be able to provide a PR with both features if required. Thanks.

**Comment by Kircheneer** [comment]
> Ideally (that may be another feature), if some projects using a cruft needs to apply some very specific changes to the template, they can either skip the whole files (which is already possible) or specify a set of patches to apply to the generated template. The patches could be specified in the cruft.json like so: {"patches": [".cruftpatches/remove-useless-feature.patch]}.

Was this also implemented as part of #59?
