### ISSUE TITLE
Update fails on new files

### ISSUE THREAD

**Issue by peldszus** [cruft/cruft#67]
**Summary:**
When adding a new file to an already existing template, the new file is not added to an instance of the template upon update.

Im running `cruft==2.5.0` here.

**Step to reproduce:**
* Have an existing template and an instance of that template.
* Add a new file to the template.
* Run `cruft update`.

**Current behaviour:**
* `cruft check` correctly detects the instance needs to be updated.
  ```
  $ cruft check
  FAILURE: Project's cruft is out of date! Run `cruft update` to clean this mess up.
  ```
* `cruft update` asks me to review a diff, but when asked to show it, it reports "no changes".
* If I apply it, it reports success, but the new file has not been added.
  ```
  $ cruft update
  Respond with "s" to intentionally skip the update while marking your project as up-to-date or respond with "v" to view the changes that   will be applied.
  Apply diff and update? (y, n, s, v) [y]: v
  There are no changes.
  Respond with "s" to intentionally skip the update while marking your project as up-to-date or respond with "v" to view the changes that   will be applied.
  Apply diff and update? (y, n, s, v) [y]: y
  Good work! Project's cruft has been updated and is as clean as possible!
  ```

**Expected behaviour of `cruft update`:**
* There is a meaningful diff shown for newly added files.
* If I accept it, the new files is created.
* Cruft should not report success if some change could not be handled correctly.

**Comment by grigorescu** [comment]
I'm seeing the same behavior, but I believe that 2.4.0 works.

**Comment by peldszus** [comment]
@samj1912 

It seems, the reason for new files not being correctly tracked is that they are recognized as `deleted_paths` and thus removed before the diff is calculated, see [here](https://github.com/cruft/cruft/blob/2.5.0/cruft/_commands/utils/generate.py#L40).

Unfortunately, the `_get_deleted_files()` method cannot differentiate between files that do not exist in the project _anymore_, because they were deliberately deleted, and files that do not exist _yet_, because they are about to be freshly added.

I am not sure whether this distinction could be made robustly in a programmatic way without introducing too much complexity.

But as an heretic alternative: Could we not do without the removal of "deleted paths" and remove that logic? :) After all, if I delete a file in my project that is part of the template and I do not want `cruft update` to re-introduce that, then I can simply put it on the `skip` list, no?

I should add that not removing new files before the diff is also part of the solution for #53, from what I understand now.

PS: Co-workers and I are currently doing a little hackathon and hoping to contribute a fix for this issue and #53 on the way. We'd be happy to hear about your stance towards that "alternative". :)

**Comment by samj1912** [comment]
Hello - sorry for the delayed response. I will investigate this over this weekend. Some initial thoughts - 

the `get_deleted_files` method does the following. Checks the `current` version of the template that the project is linked against and tries to identify files that are present in a pristine project generated from the `current` template and the ones present in the user's project. For any files that are absent, it means that those files were removed explicitly by the user and we should not update those. 

It should be able to differentiate between the two cases you mentioned above. 

> files that do not exist in the project anymore, because they were deliberately deleted, and files that do not exist yet, because they are about to be freshly added.

If the former happens, the file will be present in the "pristine" version of the cookiecutter with the current project's context and will be absent in the project. This means that the file was deleted.

If the file is absent in the "pristine" version of the currently linked template and present in the updated version, it means they were freshly added.

LMK if that makes sense.

**Comment by samj1912** [comment]
Further investigation. The above was the expected behavior. It looks like the above bug was introduced by a refactoring that took place in https://github.com/cruft/cruft/pull/59

The deleted files code was extracted to a common function - https://github.com/cruft/cruft/blob/2.5.0/cruft/_commands/utils/generate.py#L40

and was reused for both the current context and the new context https://github.com/cruft/cruft/blob/master/cruft/_commands/update.py#L68

This was not the original intention. See https://github.com/cruft/cruft/blob/2.4.0/cruft/_commands/update.py#L86

I will put in a fix soon.

**Comment by peldszus** [comment]
Hi @samj1912!

Indeed, this was a regression, adding new files was working in 2.4.0 already. (But moving files #53 was already an issue in that version.) It is good that both are now fixed.

I see how the originally intended use of `_get_deleted_files` actually solves our problem. And 
our solution for #53 looks exactly like yours. :+1:

I guess what we can learn here is that even having 100% line coverage in tests doesn't protect us from having desired functionally still left untested. :grimacing: 

Anyway, thanks for providing the fix and the release! We'll start using cruft now more often. :slightly_smiling_face:

**Comment by grigorescu** [comment]
Would it be able to cut a new release with this fix? We have some things in the queue that are waiting on this. Thanks!

**Comment by peldszus** [comment]
This is already fixed and released in `2.6.0`.

**Comment by 3lueLightning** [comment]
Hey, I am new to cruft and was experimenting with today when I faced the same issue reported here.

I'm running `cruft==2.15.0` installed using Python 3.12.2.

Step to reproduce:
* Have an existing template 
* Created an instance of that template via `cruft create https://github.com/<my_template>`.
* Added a new file to the template and pushed it to github sucessfully.
   * Note: I don't know if it relevant but it is a `.gitattributes` file.
* Ran cruft update.

Current behaviour (exactly the same as in the initial comment, copy pasted here for completeness):

    cruft check correctly detects the instance needs to be updated.

    $ cruft check
    FAILURE: Project's cruft is out of date! Run `cruft update` to clean this mess up.

    cruft update asks me to review a diff, but when asked to show it, it reports "no changes".
    If I apply it, it reports success, but the new file has not been added.

    $ cruft update
    Respond with "s" to intentionally skip the update while marking your project as up-to-date or respond with "v" to view the changes that   will be applied.
    Apply diff and update? (y, n, s, v) [y]: v
    There are no changes.
    Respond with "s" to intentionally skip the update while marking your project as up-to-date or respond with "v" to view the changes that   will be applied.
    Apply diff and update? (y, n, s, v) [y]: y
    Good work! Project's cruft has been updated and is as clean as possible!

**Comment by qckpckt** [comment]
Hey, I am also seeing this behaviour currently with `cruft==2.15.0` and `cookiecutter==2.6.0`.

**Comment by leezero-carbon** [comment]
I think I am too seeing this issue, I had to manually add back in a file that differed slightly, in order for cruft to pick up that file from the template repo and make a change to "reset" it back
