### ISSUE TITLE
Add support for cruft create/update in a sub directory in an existing repository

### ISSUE THREAD

**Issue by jakeatdrizly** [cruft/cruft#68]
cruft Version: 2.5.0

This may come across as a very basic issue, but `cruft update` isn't working as intended.

My steps were:
1) run `cruft create repo-with-cookiecutter-template` within an already existing project
2) git push the newly created project up to the repo
3) make a minor update and push the repo-with-cookiecutter-template
4) run cruft update

This shows that an update occurs, and when I enter "v" I can see a diff (a minor change to a readme)

When I enter "y" the only thing thing that gets update is .cruft.json and the diff is not applied.

Feels like there must be some basic step I'm missing but the docs don't show anything and the closed issues don't seem to have this as an issue.

Any help would be much appreciated.

Thanks

**Comment by samj1912** [comment]
cruft currently doesn't work for new projects that were created as sub-directories in existing git projects. This will require some changes in the way cruft calculates diffs and does updates and is an enhancement. Meanwhile I think cruft should be explicit if it detects the `.cruft.json` in an existing git repo and show a warning that it won't work for updates.

**Comment by jakeatdrizly** [comment]
So in it's current form I should move the project from an existing repo to a new repo where the only thing in the repo is the result a cruft create call?

**Comment by samj1912** [comment]
@jakeatdrizly that is correct :)
