### ISSUE TITLE
Bug: .cruft.json file created with trailing new line

### ISSUE THREAD

**Issue by lyz-code** [cruft/cruft#75]
Hi, the `.cruft.json` file get's created with a trailing new line at the end of the file. Which conflicts with the `end-of-file-fixer`

```
Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing .cruft.json
```

If we do a git diff:

```
diff --git a/.cruft.json b/.cruft.json
index 60d62c3..fa34b58 100644
--- a/.cruft.json
+++ b/.cruft.json
@@ -21,4 +21,4 @@
         }
     },
     "directory": null
-}
\ No newline at end of file
+}
```

It would be nice if the last line didn't have that trailing newline.

After diving into the json_dumps options, I see that with `indent=None` it is fixed although you probably don't want that. Adding `.strip()` to the `json_dumps` function in `utils` doesn't solve it either.

Thanks

**Comment by lyz-code** [comment]
I've seen that the problem is not on the `json_dumps` but on how `Path` writes to the file

**Comment by cjolowicz** [comment]
It's actually the other way round: cruft does not terminate `.cruft.json` with a newline, which causes the pre-commit failure. Note that `json.dump` from the standard library does not add a final newline, even when passed `indent`.

I would also like to see this fixed.
