### ISSUE TITLE
Support Updating When Repo has Untracked Files (But No Other Changes)

### ISSUE THREAD

**Issue by aperiodic** [cruft/cruft#91]
First off, I wanted to say thank you for making and maintaining cruft! We're using a python project template at work for all of the python development in our department, and it uses cookiecutter. The primary point of friction with it is it's a _lot_ of work to updating existing projects when we make changes to the template, since we have more projects than maintainers. @tdhopper recently clued me in to cruft, and it seems perfectly designed to alleviate this problem for us!

I wanted to ask whether you would be open to a behavior change for `cruft update`. Right now, it refuses to run if the git repo is not perfectly clean. I understand the motivation for this, as it's not perfectly safe to apply the changes from the linked template otherwise. However, most of the users of our template are researchers, and they tend to have lots of ad-hoc files in their repo (chart outputs, notes, etc.). Because of this, cruft's current behavior makes it hard for us to adopt.

The change I would like to make is to add a flag, something like `--allow-unsafe-update`, that would allow `cruft update` to run if there are untracked files in the repo but no changes to tracked files. I want the name and all associated documentation to clearly indicate that this involves some danger, and if you use this and lose data/work it's your problem (in our use case, we would look at the untracked files to make sure none of them could possibly be overwritten by template changes).

What do you think about this proposal?

**Comment by samj1912** [comment]
@aperiodic thanks for the feedback. Addition of this flag and supporting this usecase sound good to me!  Would you be able to contribute this change?

**Comment by aperiodic** [comment]
Yes, I would! I'm only working on this during work hours, so I don't anticipate having a PR ready until middle of next week (in UTC-8 / US West Coast time).

**Comment by tdhopper** [comment]
@aperiodic Let me know if you want to pair on this for a bit.

**Comment by samj1912** [comment]
Fixed by #95
