### ISSUE TITLE
cruft create not creating a .cruft.json file

### ISSUE THREAD

**Issue by kevinmstephens** [cruft/cruft#93]
cruft   Version: 2.7.0
Python 3.9.1
macos 10.15.7
using zsh

When I run cruft create and complete the prompts
- I see a ton of data going to stdout. This doesn't seem correct...
- When I cd into the generated folder I see all files but not a `.cruft.json`

I can use `cruft link` to generate a `cruft.json` as a workaround.

**Comment by samj1912** [comment]
I have not encountered this before. Can you give a little more information about the cookiecutter template you are using?
