### ISSUE TITLE
cruft update writing to STDOUT and not showing interactive mode

### ISSUE THREAD

**Issue by kevinmstephens** [cruft/cruft#94]
cruft Version: 2.7.0
Python 3.9.1
macos 10.15.7
using zsh

I'm using 
- cruft update -c target-branch
- I see a ton of content going to STDOUT (I think it's all of the template data)
- process exits. I see no interactive prompt and I don't see changes stages in the git repo

**Comment by sambhav** [comment]
Given the lack of information in this issue, I am closing this.
