### ISSUE TITLE
Feature Request: provide docker image

### ISSUE THREAD

**Issue by dhruvkhanna38** [cruft/cruft#97]

**Comment by regicsolutions** [comment]
Also looking for a Docker image as well. Is cookiecutter a prerequisite to be installed prior to using cruft or is it already baked into cruft where you only need a single install?

**Comment by jonzarecki** [comment]
coockiecutter is a prerequisite stated in the dependencies, so only a single install is needed.

**Comment by sharadpattanshetti** [comment]
Hi, I am trying to create docker image for cruft. We see that  `cruft update` command opens interactive mode for git credentials, is there a way to set these arguments and  avoid interactive mode?

**Comment by camabeh** [comment]
You could try to use ssh keys. You will need to mount them to ~/.ssh.
